=== nadigeri/ICDOQV_XMLgyak/ICDOQV_0928/NG_orarend.dtd
<!ELEMENT orarend (napok*)>
    <!ELEMENT napok (ora*)>
        <!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
            <!ELEMENT targy (#PCDATA)>
            <!ELEMENT idopont (nap, tol, ig)>
                <!ELEMENT nap (#PCDATA)>
                <!ELEMENT tol (#PCDATA)>
                <!ELEMENT ig (#PCDATA)>
            <!ELEMENT helyszin (#PCDATA)>
            <!ELEMENT oktato (#PCDATA)>
            <!ELEMENT szak (#PCDATA)>
        <!ATTLIST napok id CDATA #REQUIRED>
        <!ATTLIST napok nev CDATA #REQUIRED>
        <!ATTLIST ora id CDATA #REQUIRED>
        <!ATTLIST ora tÃ­pus CDATA #REQUIRED>

=== nadigeri/ICDOQV_XMLgyak/ICDOQV_0928/NG_orarend.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE orarend SYSTEM "NG_orarend.dtd">

<orarend>
    <napok id="1" nev="Hétfő">
	    <ora id="1" típus="elmelet" >
		    <targy>Algoritmusok és Viszgálatuk elmélet</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>8:00</tol>
			    <ig>10:00</ig>
		    </idopont>
		    <helyszin>A3 313.</helyszin>
		    <oktato> Dr. Házy Attila</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="2" típus="gyakorlat" >
		    <targy>Algoritmusok és Viszgálatuk gyakorlat</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>10:00</tol>
			    <ig>12:00</ig>
		    </idopont>
		    <helyszin>A3 313.</helyszin>
		    <oktato> Dr. Házy Attila</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="3" típus="elmelet" >
		    <targy>WEB technologiak elmélet</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>12:00</tol>
			    <ig>14:00</ig>
		    </idopont>
		    <helyszin>A1 305.</helyszin>
		    <oktato>Agárdi Anita</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="4" típus="elmélet" >
		    <targy>Mesterséges Intelligencia elmélet</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>14:00</tol>
			    <ig>17:00</ig>
		    </idopont>
		    <helyszin>XXXII.</helyszin>
		    <oktato>Dr. Dudás László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>
    </napok>

    <napok id="2" nev="Kedd">
        <ora id="5" típus="elmélet" >
		    <targy>XML adatkezelés elmélet</targy>
		    <idopont>
			    <nap>Kedd</nap>
			    <tol>12:00</tol>
			    <ig>14:00</ig>
		    </idopont>
		    <helyszin>I.</helyszin>
		    <oktato>Dr. Bednarik László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="6" típus="gyakorlat" >
		    <targy>XML adatkezelés gyakorlat</targy>
		    <idopont>
			    <nap>Kedd</nap>
			    <tol>14:00</tol>
			    <ig>16:00</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Dr. Bednarik László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="7" típus="gyakorlat" >
		    <targy>WEB technológiák gyakorlat</targy>
		    <idopont>
			    <nap>Kedd</nap>
			    <tol>18:00</tol>
			    <ig>20:00</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Agárdi Anita</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>
    </napok>

    <napok id="8" nev="Szerda">
        <ora id="9" típus="gyakorlat" >
		    <targy>Mesterséges Intelligencia gyakorlat</targy>
		    <idopont>
			    <nap>Szerda</nap>
			    <tol>9:00</tol>
			    <ig>10:00</ig>
		    </idopont>
		    <helyszin>Inf. 15.</helyszin>
		    <oktato>Dr. Dudás László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="9" típus="elmélet" >
		    <targy>Vállalati Információs Rendszerek elmélet</targy>
		    <idopont>
			    <nap>Szerda</nap>
			    <tol>16:00</tol>
			    <ig>18:00</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Dr. Sasvári Péter</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="10" típus="gyakorlat" >
		    <targy>Vállalati Információs Rendszerek gyakorlat</targy>
		    <idopont>
			    <nap>Szerda</nap>
			    <tol>18:00</tol>
			    <ig>20:00</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Dr. Sasvári Péter</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>
    </napok>
</orarend>
