=== nadigeri/ICDOQV_XMLgyak/ICDOQV_1005/NG_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://www.w3schools.com" elementFormDefault="qualified">
    <xs:element name="konyvek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="konyv" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cim" type="xs:string"/>
                            <xs:element name="kiadasiev" type="xs:unsignedShort"/>
                            <xs:element name="kiado" type="xs:string"/>
                            <xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="abstract" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nadigeri/ICDOQV_XMLgyak/ICDOQV_1005/NG_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE konyvek SYSTEM "HD_konyv.dtd"> -->

<konyvek 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="NG_konyv.xsd">
	<konyv id="1" >
		<cim>Clean Code</cim>
		<kiadasiev>2008</kiadasiev>
		<kiado>&lt;XML&gt; Robert C. Martin</kiado>
		<szerzo>Robert C. Martin</szerzo>
        <abstract>Book for clean coding.</abstract>
	</konyv>
	
	<konyv id="2" >
		<cim>Clean Architecture</cim>
		<kiadasiev>2017</kiadasiev>
		<kiado>&lt;XML&gt; Robert C. Martin</kiado>
		<szerzo>Robert C. Martin</szerzo>
		<abstract>Book for coding.</abstract>
	</konyv>
</konyvek>
