=== nadigeri/ICDOQV_XMLgyak/ICDOQV_1012/NG_orarend1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="orarend"> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="napok" type="napokType"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="napokType">
        <xs:sequence>
            <xs:element name="ora" type="oraType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="nev" type="napType" default="Hétfő"/>
    </xs:complexType>

    <xs:complexType name="oraType">
        <xs:sequence>
            <xs:element name="targy" type="xs:string"/>
            <xs:element name="idopont" type="idopontType"/>
            <xs:element name="helyszin" type="xs:string"/>
            <xs:element name="oktato" type="xs:string"/>
            <xs:element name="szak" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="típus" type="oratipusType"/>
    </xs:complexType>

    <xs:simpleType name="oratipusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="elmelet"/>
            <xs:enumeration value="gyakorlat"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="idopontType">
        <xs:sequence>
            <xs:element name="nap" type="napType"/>
            <xs:element name="tol" type="tolType"/>
            <xs:element name="ig" type="igType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="napType">
            <xs:restriction base="xs:string">
                <xs:enumeration value="Hétfő"/>
                <xs:enumeration value="Kedd"/>
                <xs:enumeration value="Szerda"/>
                <xs:enumeration value="Csütörtök"/>
                <xs:enumeration value="Péntek"/>
            </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tolType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="8"/>
            <xs:maxInclusive value="18"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="igType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="10"/>
            <xs:maxInclusive value="20"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== nadigeri/ICDOQV_XMLgyak/ICDOQV_1012/NG_orarend1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="NG_orarend1.xsd">
    <napok id="1" nev="Hétfő">
	    <ora id="1" típus="elmelet" >
		    <targy>Algoritmusok és Viszgálatuk elmélet</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>8</tol>
			    <ig>10</ig>
		    </idopont>
		    <helyszin>A3 313.</helyszin>
		    <oktato>Dr. Házy Attila</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="2" típus="gyakorlat" >
		    <targy>Algoritmusok és Viszgálatuk gyakorlat</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>10</tol>
			    <ig>12</ig>
		    </idopont>
		    <helyszin>A3 313.</helyszin>
		    <oktato> Dr. Házy Attila</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="3" típus="elmelet" >
		    <targy>WEB technologiak elmélet</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>12</tol>
			    <ig>14</ig>
		    </idopont>
		    <helyszin>A1 305.</helyszin>
		    <oktato>Agárdi Anita</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="4" típus="elmelet" >
		    <targy>Mesterséges Intelligencia elmélet</targy>
		    <idopont>
			    <nap>Hétfő</nap>
			    <tol>14</tol>
			    <ig>17</ig>
		    </idopont>
		    <helyszin>XXXII.</helyszin>
		    <oktato>Dr. Dudás László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>
    </napok>

    <napok id="2" nev="Kedd">
        <ora id="5" típus="elmelet" >
		    <targy>XML adatkezelés elmélet</targy>
		    <idopont>
			    <nap>Kedd</nap>
			    <tol>12</tol>
			    <ig>14</ig>
		    </idopont>
		    <helyszin>I.</helyszin>
		    <oktato>Dr. Bednarik László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="6" típus="gyakorlat" >
		    <targy>XML adatkezelés gyakorlat</targy>
		    <idopont>
			    <nap>Kedd</nap>
			    <tol>14</tol>
			    <ig>16</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Dr. Bednarik László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="7" típus="gyakorlat" >
		    <targy>WEB technológiák gyakorlat</targy>
		    <idopont>
			    <nap>Kedd</nap>
			    <tol>18</tol>
			    <ig>20</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Agárdi Anita</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>
    </napok>

    <napok id="3" nev="Szerda">
        <ora id="8" típus="gyakorlat" >
		    <targy>Mesterséges Intelligencia gyakorlat</targy>
		    <idopont>
			    <nap>Szerda</nap>
			    <tol>9</tol>
			    <ig>10</ig>
		    </idopont>
		    <helyszin>Inf. 15.</helyszin>
		    <oktato>Dr. Dudás László</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="9" típus="elmelet" >
		    <targy>Vállalati Információs Rendszerek elmélet</targy>
		    <idopont>
			    <nap>Szerda</nap>
			    <tol>16</tol>
			    <ig>18</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Dr. Sasvári Péter</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>

        <ora id="10" típus="gyakorlat" >
		    <targy>Vállalati Információs Rendszerek gyakorlat</targy>
		    <idopont>
			    <nap>Szerda</nap>
			    <tol>18</tol>
			    <ig>20</ig>
		    </idopont>
		    <helyszin>Inf. 103.</helyszin>
		    <oktato>Dr. Sasvári Péter</oktato>
		    <szak>Programtervező Informatika</szak>
	    </ora>
    </napok>
</orarend>
